version: '3.8'
services:
  geth:
    image: ethereum/client-go:stable
    command: >
      --dev
      --http
      --http.addr 0.0.0.0
      --http.vhosts=*
      --http.api web3,eth,net
    ports:
      - "8545:8545"
    volumes:
      - ./geth-data:/root/.ethereum
